name: Build documentation

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  # Name of module and id separated by a slash
  INSTANCE_FR: Writerside/wiki
  INSTANCE_EN: Writerside/wiki-en
  # Replace HI with the ID of the instance in capital letters
  ARTIFACT_FR: webHelpWIKI2-all.zip
  ARTIFACT_EN: webHelpWIKI-EN2-all.zip
  # Writerside docker image version
  DOCKER_VERSION: 233.14272
  # Algolia
  ALGOLIA_APP_NAME: QI35XH8YI5
  ALGOLIA_INDEX_NAME_FR: Wiki-FR
  ALGOLIA_KEY: ${{ secrets.ALGOLIA_KEY }}
  ALGOLIA_ARTIFACT_FR: algolia-indexes-WIKI.zip
  CONFIG_JSON_PRODUCT_FR: fr
  CONFIG_JSON_VERSION_FR: 0.0.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Writerside docs using Docker
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE_FR }}
          artifact: ${{ env.ARTIFACT_FR }}
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Unzip artifact
        run: mkdir wiki && unzip -q artifacts/${{ env.ARTIFACT_FR }} -d wiki/fr

      - name: Upload algolia-indexes
        uses: actions/upload-artifact@v3
        with:
          name: algolia-indexes-fr
          path: artifacts/${{ env.ALGOLIA_ARTIFACT_FR }}
          retention-days: 7

      - name: Build Writerside docs using Docker
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE_EN }}
          artifact: ${{ env.ARTIFACT_EN }}
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Unzip artifact
        run: unzip -q artifacts/${{ env.ARTIFACT_EN }} -d wiki/en

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: wiki
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          REMOTE_PORT: ${{ secrets.PORT }}
          TARGET: ${{ secrets.REMOTE_TARGET }}

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo rm -rf ${{ secrets.DEPLOYMENT_TARGET }}
            sudo mv ${{ secrets.REMOTE_TARGET }}/wiki ${{ secrets.DEPLOYMENT_TARGET }}

  publish-indexes:
    # Requires the build-job results
    needs: build
    runs-on: ubuntu-latest
    container:
      image: registry.jetbrains.team/p/writerside/builder/algolia-publisher:2.0.32-2

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: algolia-indexes-fr
      - name: Display files
        run: ls -la
      - name: Unzip artifact
        run: |
          unzip -O UTF-8 -qq ${{ env.ALGOLIA_ARTIFACT_FR }} -d algolia-indexes-fr
          env "algolia-key=${{env.ALGOLIA_KEY}}" java -jar /opt/builder/help-publication-agent.jar \
          update-index \
          --application-name ${{env.ALGOLIA_APP_NAME}} \
          --index-name ${{env.ALGOLIA_INDEX_NAME_FR}} \
          --product ${{env.CONFIG_JSON_PRODUCT_FR}} \
          --version ${{env.CONFIG_JSON_VERSION_FR}} \
          --index-directory algolia-indexes-fr/ \
          2>&1 | tee algolia-update-index-log.txt